name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [feature/staging]

# Set needed env variables
env:
  DBT_PROFILE_TARGET: dev
  DBT_PROFILE_USER: ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PROFILE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dbt packages
        run: dbt deps

      - name: Run dbt test
        run: dbt test
